# Generated by Django 4.0 on 2023-12-20 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=300, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('telefone', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=300, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('cep', models.CharField(max_length=10)),
                ('rua', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=40)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=50, null=True)),
                ('cidade', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=15)),
                ('pais', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=300, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=300, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('cnpj', models.CharField(max_length=14)),
                ('inscricao_estadual', models.CharField(max_length=9)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=300, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.CharField(choices=[('FISICA', 'Física'), ('JURIDICA', 'Jurídica')], default='', max_length=10)),
                ('pessoa_fisica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes_fisicos', to='pessoas.pessoafisica', verbose_name='Pessoa Física')),
                ('pessoa_juridica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes_juridicos', to='pessoas.pessoajuridica', verbose_name='Pessoa Jurídica')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=300, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=50)),
                ('ativo', models.BooleanField()),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_contato', to='pessoas.contato', verbose_name='Contato')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_endereco', to='pessoas.endereco', verbose_name='Endereco')),
                ('tipo_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_pessoa_cliente', to='pessoas.tipopessoa', verbose_name='Tipo Pessoa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
