# Generated by Django 4.0 on 2023-12-20 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiros', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=300, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('nome_parametro', models.CharField(max_length=45, unique=True)),
                ('valor_parametro', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TA_Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=300, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=50)),
                ('tipo_maquinario', models.CharField(choices=[('Pulverizador', 'Pulverizador'), ('Distribuidor', 'Distribuidor')], default='', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TA_Versao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=300, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=50)),
                ('preco_venda', models.BigIntegerField()),
                ('upgrade', models.BooleanField(default=False)),
                ('imagem_nome', models.CharField(max_length=50)),
                ('capa_nome', models.CharField(max_length=50)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelo_versao', to='gerador_proposta.ta_modelo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TB_GrupoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=300, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=50)),
                ('tipo_maquinario', models.CharField(choices=[('Pulverizador', 'Pulverizador'), ('Distribuidor', 'Distribuidor'), ('Universal', 'Universal')], default='', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TB_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=50)),
                ('preco_custo', models.BigIntegerField()),
                ('observacao', models.TextField(blank=True)),
                ('upgrade', models.BooleanField(default=False)),
                ('codigo_upgrade', models.IntegerField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_item', to='gerador_proposta.tb_grupoitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TBA_ItensUpgradeVersaoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=300, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_versao_upgrade', to='gerador_proposta.tb_item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TC_AlcadaLiberacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=300, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('data_finalizacao', models.DateTimeField(null=True)),
                ('status_leitura', models.BooleanField(default=False)),
                ('status_alcada', models.CharField(default='pendente', max_length=30)),
                ('justificativa', models.CharField(max_length=300, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TCD_AlcadasProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=300, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('alcada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alcada_proposta', to='gerador_proposta.tc_alcadaliberacao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TD_PropostaTecnicoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=300, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('alcada_liberacao', models.ManyToManyField(related_name='alcadas_liberacao', through='gerador_proposta.TCD_AlcadasProposta', to='gerador_proposta.TC_AlcadaLiberacao')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autor_proposta', to='auth.user')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gerador_proposta_cliente', to='pessoas.cliente')),
                ('financeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gerador_proposta_financeiro_proposta', to='financeiros.financeiroproposta')),
                ('itens_upgrade', models.ManyToManyField(related_name='proposta_item_versao_upgrade', through='gerador_proposta.TBA_ItensUpgradeVersaoMaquina', to='gerador_proposta.TB_Item')),
                ('modelo_maquina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelo_maquina_proposta', to='gerador_proposta.ta_modelo')),
                ('versao_maquina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versao_maquina_proposta', to='gerador_proposta.ta_versao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tcd_alcadasproposta',
            name='proposta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposta_alcada', to='gerador_proposta.td_propostatecnicocomercial'),
        ),
        migrations.CreateModel(
            name='TC_TipoAlcada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=300, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('nome_alcada', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=50)),
                ('responsavel_alcada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alcada_responsavel', to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tc_alcadaliberacao',
            name='tipo_alcada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_alcada', to='gerador_proposta.tc_tipoalcada'),
        ),
        migrations.CreateModel(
            name='TBA_ItensVersao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=300, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('quantidade', models.IntegerField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_versao', to='gerador_proposta.tb_item')),
                ('versao_modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versao_modelo', to='gerador_proposta.ta_versao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tba_itensupgradeversaomaquina',
            name='proposta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposta', to='gerador_proposta.td_propostatecnicocomercial'),
        ),
        migrations.AddField(
            model_name='ta_versao',
            name='tabela_itens',
            field=models.ManyToManyField(related_name='itens_versao', through='gerador_proposta.TBA_ItensVersao', to='gerador_proposta.TB_Item'),
        ),
    ]
