# Generated by Django 4.0 on 2024-01-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerador_proposta', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='ta_versao',
        #     name='data_atualizacao',
        # ),
        # migrations.RemoveField(
        #     model_name='ta_versao',
        #     name='data_criacao',
        # ),
        # migrations.RemoveField(
        #     model_name='ta_versao',
        #     name='observacao',
        # ),
    ]
