# Generated by Django 4.0 on 2024-01-15 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gerador_proposta', '0002_remove_ta_versao_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ta_versao',
            name='data_atualizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ta_versao',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ta_versao',
            name='observacao',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
