# Generated by Django 4.0 on 2024-01-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerador_proposta', '0004_alter_parametros_data_criacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ta_versao',
            name='tabela_itens',
        ),
        migrations.DeleteModel(
            name='TBA_ItensVersao',
        ),
    ]
