# Generated by Django 4.0 on 2024-01-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerador_proposta', '0006_tba_itensversao_ta_versao_tabela_itens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='td_propostatecnicocomercial',
            name='modelo_maquina',
        ),
    ]
