# Generated by Django 4.0 on 2024-02-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerador_proposta', '0007_remove_td_propostatecnicocomercial_modelo_maquina'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='tb_grupoitem',
        #     name='data_atualizacao',
        # ),
        # migrations.RemoveField(
        #     model_name='tb_grupoitem',
        #     name='data_criacao',
        # ),
        # migrations.RemoveField(
        #     model_name='tb_grupoitem',
        #     name='observacao',
        # ),
    ]
