# Generated by Django 4.0 on 2023-12-20 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddImplemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormaPagmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.CharField(choices=[('DINHEIRO', 'dinheiro'), ('CHEQUE', 'cheque'), ('BOLETO', 'boleto'), ('PIX', 'pix'), ('TED', 'ted'), ('DOC', 'doc'), ('CARTÃO DE CRÉDITO', 'cartao de credito'), ('CARTÃO DE DÉBITO', 'cartao de debito')], default='', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PgmentoFinanciamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PgmentoRecursoProprio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('bool_avista', models.BooleanField(default=False)),
                ('bool_parcelado', models.BooleanField(default=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qntdade_parcelas', models.CharField(max_length=5, null=True)),
                ('forma_pgmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurso_proprio_forma_pagamento', to='financeiros.formapagmento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinanceiroProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tb_add_implemento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financeiro_add_implemento', to='financeiros.addimplemento')),
                ('tb_pgmento_financiamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financeiro_modo_financiamento', to='financeiros.pgmentofinanciamento')),
                ('tb_pgmento_recurso_proprio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financeiro_modo_recurso_proprio', to='financeiros.pgmentorecursoproprio')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pgmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrada_forma_pagamento', to='financeiros.formapagmento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
